### ISSUE TITLE
DI registration issue

### ISSUE THREAD

**Issue by steveoh** [shaunluttin/asp-net-core-health-check-dependency-injection#1]
```cs
services.AddSingleton<IHealthCheck, SomeHealthCheck>();
```
is required like you demonstrated in SO. 

```cs
services.AddSingleton<SomeHealthCheck>();
```
is ignored by the health checks.

**Comment by shaunluttin** [comment]
Fixed with https://github.com/shaunluttin/asp-net-core-health-check-dependency-injection/commit/ef5a86b3986ae80ae42e664ec20b8e6f6cbd7e01.
